/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MockTestsIndexRouteImport } from './routes/mock-tests.index'
import { Route as UPublicIdRouteImport } from './routes/u.$publicId'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPracticeIndexRouteImport } from './routes/_authenticated/practice.index'
import { Route as MockTestsTestIdWarningRouteImport } from './routes/mock-tests.$testId.warning'
import { Route as MockTestsTestIdRunRouteImport } from './routes/mock-tests.$testId.run'
import { Route as MockTestsTestIdResultRouteImport } from './routes/mock-tests.$testId.result'
import { Route as AuthenticatedPracticeQidRouteImport } from './routes/_authenticated/practice.$qid'
import { Route as AuthenticatedAdminAiMockRouteImport } from './routes/_authenticated/admin_.ai-mock'
import { Route as MockTestsAiTestIdWarningRouteImport } from './routes/mock-tests.ai.$testId.warning'
import { Route as MockTestsAiTestIdTakeRouteImport } from './routes/mock-tests.ai.$testId.take'
import { Route as MockTestsAiTestIdResultRouteImport } from './routes/mock-tests.ai.$testId.result'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MockTestsIndexRoute = MockTestsIndexRouteImport.update({
  id: '/mock-tests/',
  path: '/mock-tests/',
  getParentRoute: () => rootRouteImport,
} as any)
const UPublicIdRoute = UPublicIdRouteImport.update({
  id: '/u/$publicId',
  path: '/u/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPracticeIndexRoute =
  AuthenticatedPracticeIndexRouteImport.update({
    id: '/practice/',
    path: '/practice/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const MockTestsTestIdWarningRoute = MockTestsTestIdWarningRouteImport.update({
  id: '/mock-tests/$testId/warning',
  path: '/mock-tests/$testId/warning',
  getParentRoute: () => rootRouteImport,
} as any)
const MockTestsTestIdRunRoute = MockTestsTestIdRunRouteImport.update({
  id: '/mock-tests/$testId/run',
  path: '/mock-tests/$testId/run',
  getParentRoute: () => rootRouteImport,
} as any)
const MockTestsTestIdResultRoute = MockTestsTestIdResultRouteImport.update({
  id: '/mock-tests/$testId/result',
  path: '/mock-tests/$testId/result',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPracticeQidRoute =
  AuthenticatedPracticeQidRouteImport.update({
    id: '/practice/$qid',
    path: '/practice/$qid',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAiMockRoute =
  AuthenticatedAdminAiMockRouteImport.update({
    id: '/admin_/ai-mock',
    path: '/admin/ai-mock',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const MockTestsAiTestIdWarningRoute =
  MockTestsAiTestIdWarningRouteImport.update({
    id: '/mock-tests/ai/$testId/warning',
    path: '/mock-tests/ai/$testId/warning',
    getParentRoute: () => rootRouteImport,
  } as any)
const MockTestsAiTestIdTakeRoute = MockTestsAiTestIdTakeRouteImport.update({
  id: '/mock-tests/ai/$testId/take',
  path: '/mock-tests/ai/$testId/take',
  getParentRoute: () => rootRouteImport,
} as any)
const MockTestsAiTestIdResultRoute = MockTestsAiTestIdResultRouteImport.update({
  id: '/mock-tests/ai/$testId/result',
  path: '/mock-tests/ai/$testId/result',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/u/$publicId': typeof UPublicIdRoute
  '/mock-tests/': typeof MockTestsIndexRoute
  '/admin/ai-mock': typeof AuthenticatedAdminAiMockRoute
  '/practice/$qid': typeof AuthenticatedPracticeQidRoute
  '/mock-tests/$testId/result': typeof MockTestsTestIdResultRoute
  '/mock-tests/$testId/run': typeof MockTestsTestIdRunRoute
  '/mock-tests/$testId/warning': typeof MockTestsTestIdWarningRoute
  '/practice/': typeof AuthenticatedPracticeIndexRoute
  '/mock-tests/ai/$testId/result': typeof MockTestsAiTestIdResultRoute
  '/mock-tests/ai/$testId/take': typeof MockTestsAiTestIdTakeRoute
  '/mock-tests/ai/$testId/warning': typeof MockTestsAiTestIdWarningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/u/$publicId': typeof UPublicIdRoute
  '/mock-tests': typeof MockTestsIndexRoute
  '/admin/ai-mock': typeof AuthenticatedAdminAiMockRoute
  '/practice/$qid': typeof AuthenticatedPracticeQidRoute
  '/mock-tests/$testId/result': typeof MockTestsTestIdResultRoute
  '/mock-tests/$testId/run': typeof MockTestsTestIdRunRoute
  '/mock-tests/$testId/warning': typeof MockTestsTestIdWarningRoute
  '/practice': typeof AuthenticatedPracticeIndexRoute
  '/mock-tests/ai/$testId/result': typeof MockTestsAiTestIdResultRoute
  '/mock-tests/ai/$testId/take': typeof MockTestsAiTestIdTakeRoute
  '/mock-tests/ai/$testId/warning': typeof MockTestsAiTestIdWarningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/u/$publicId': typeof UPublicIdRoute
  '/mock-tests/': typeof MockTestsIndexRoute
  '/_authenticated/admin_/ai-mock': typeof AuthenticatedAdminAiMockRoute
  '/_authenticated/practice/$qid': typeof AuthenticatedPracticeQidRoute
  '/mock-tests/$testId/result': typeof MockTestsTestIdResultRoute
  '/mock-tests/$testId/run': typeof MockTestsTestIdRunRoute
  '/mock-tests/$testId/warning': typeof MockTestsTestIdWarningRoute
  '/_authenticated/practice/': typeof AuthenticatedPracticeIndexRoute
  '/mock-tests/ai/$testId/result': typeof MockTestsAiTestIdResultRoute
  '/mock-tests/ai/$testId/take': typeof MockTestsAiTestIdTakeRoute
  '/mock-tests/ai/$testId/warning': typeof MockTestsAiTestIdWarningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/admin'
    | '/analytics'
    | '/leaderboard'
    | '/notifications'
    | '/profile'
    | '/u/$publicId'
    | '/mock-tests/'
    | '/admin/ai-mock'
    | '/practice/$qid'
    | '/mock-tests/$testId/result'
    | '/mock-tests/$testId/run'
    | '/mock-tests/$testId/warning'
    | '/practice/'
    | '/mock-tests/ai/$testId/result'
    | '/mock-tests/ai/$testId/take'
    | '/mock-tests/ai/$testId/warning'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/admin'
    | '/analytics'
    | '/leaderboard'
    | '/notifications'
    | '/profile'
    | '/u/$publicId'
    | '/mock-tests'
    | '/admin/ai-mock'
    | '/practice/$qid'
    | '/mock-tests/$testId/result'
    | '/mock-tests/$testId/run'
    | '/mock-tests/$testId/warning'
    | '/practice'
    | '/mock-tests/ai/$testId/result'
    | '/mock-tests/ai/$testId/take'
    | '/mock-tests/ai/$testId/warning'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/leaderboard'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/u/$publicId'
    | '/mock-tests/'
    | '/_authenticated/admin_/ai-mock'
    | '/_authenticated/practice/$qid'
    | '/mock-tests/$testId/result'
    | '/mock-tests/$testId/run'
    | '/mock-tests/$testId/warning'
    | '/_authenticated/practice/'
    | '/mock-tests/ai/$testId/result'
    | '/mock-tests/ai/$testId/take'
    | '/mock-tests/ai/$testId/warning'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  UPublicIdRoute: typeof UPublicIdRoute
  MockTestsIndexRoute: typeof MockTestsIndexRoute
  MockTestsTestIdResultRoute: typeof MockTestsTestIdResultRoute
  MockTestsTestIdRunRoute: typeof MockTestsTestIdRunRoute
  MockTestsTestIdWarningRoute: typeof MockTestsTestIdWarningRoute
  MockTestsAiTestIdResultRoute: typeof MockTestsAiTestIdResultRoute
  MockTestsAiTestIdTakeRoute: typeof MockTestsAiTestIdTakeRoute
  MockTestsAiTestIdWarningRoute: typeof MockTestsAiTestIdWarningRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-tests/': {
      id: '/mock-tests/'
      path: '/mock-tests'
      fullPath: '/mock-tests/'
      preLoaderRoute: typeof MockTestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$publicId': {
      id: '/u/$publicId'
      path: '/u/$publicId'
      fullPath: '/u/$publicId'
      preLoaderRoute: typeof UPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice/': {
      id: '/_authenticated/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof AuthenticatedPracticeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/mock-tests/$testId/warning': {
      id: '/mock-tests/$testId/warning'
      path: '/mock-tests/$testId/warning'
      fullPath: '/mock-tests/$testId/warning'
      preLoaderRoute: typeof MockTestsTestIdWarningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-tests/$testId/run': {
      id: '/mock-tests/$testId/run'
      path: '/mock-tests/$testId/run'
      fullPath: '/mock-tests/$testId/run'
      preLoaderRoute: typeof MockTestsTestIdRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-tests/$testId/result': {
      id: '/mock-tests/$testId/result'
      path: '/mock-tests/$testId/result'
      fullPath: '/mock-tests/$testId/result'
      preLoaderRoute: typeof MockTestsTestIdResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/practice/$qid': {
      id: '/_authenticated/practice/$qid'
      path: '/practice/$qid'
      fullPath: '/practice/$qid'
      preLoaderRoute: typeof AuthenticatedPracticeQidRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin_/ai-mock': {
      id: '/_authenticated/admin_/ai-mock'
      path: '/admin/ai-mock'
      fullPath: '/admin/ai-mock'
      preLoaderRoute: typeof AuthenticatedAdminAiMockRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/mock-tests/ai/$testId/warning': {
      id: '/mock-tests/ai/$testId/warning'
      path: '/mock-tests/ai/$testId/warning'
      fullPath: '/mock-tests/ai/$testId/warning'
      preLoaderRoute: typeof MockTestsAiTestIdWarningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-tests/ai/$testId/take': {
      id: '/mock-tests/ai/$testId/take'
      path: '/mock-tests/ai/$testId/take'
      fullPath: '/mock-tests/ai/$testId/take'
      preLoaderRoute: typeof MockTestsAiTestIdTakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-tests/ai/$testId/result': {
      id: '/mock-tests/ai/$testId/result'
      path: '/mock-tests/ai/$testId/result'
      fullPath: '/mock-tests/ai/$testId/result'
      preLoaderRoute: typeof MockTestsAiTestIdResultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdminAiMockRoute: typeof AuthenticatedAdminAiMockRoute
  AuthenticatedPracticeQidRoute: typeof AuthenticatedPracticeQidRoute
  AuthenticatedPracticeIndexRoute: typeof AuthenticatedPracticeIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdminAiMockRoute: AuthenticatedAdminAiMockRoute,
  AuthenticatedPracticeQidRoute: AuthenticatedPracticeQidRoute,
  AuthenticatedPracticeIndexRoute: AuthenticatedPracticeIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  UPublicIdRoute: UPublicIdRoute,
  MockTestsIndexRoute: MockTestsIndexRoute,
  MockTestsTestIdResultRoute: MockTestsTestIdResultRoute,
  MockTestsTestIdRunRoute: MockTestsTestIdRunRoute,
  MockTestsTestIdWarningRoute: MockTestsTestIdWarningRoute,
  MockTestsAiTestIdResultRoute: MockTestsAiTestIdResultRoute,
  MockTestsAiTestIdTakeRoute: MockTestsAiTestIdTakeRoute,
  MockTestsAiTestIdWarningRoute: MockTestsAiTestIdWarningRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
